CREATE USER 'searchapp_user'@'localhost' IDENTIFIED BY '123';
CREATE DATABASE searchapp CHARACTER SET utf8;
GRANT ALL PRIVILEGES ON * . * TO 'searchapp_user'@'localhost' WITH GRANT OPTION;


USE searchapp;

CREATE TABLE topic (
	id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(80) NULL DEFAULT NULL,
	description VARCHAR(5000) NULL DEFAULT NULL,
	text_field1 VARCHAR(5000) NULL DEFAULT NULL,
	text_field2 VARCHAR(5000) NULL DEFAULT NULL,
	created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
)
ENGINE=InnoDB;